### ISSUE TITLE
ejdb another crash at WAL

### ISSUE THREAD

**Issue by blueshame** [Softmotions/ejdb#364] opened 2022-11-09 16:57 UTC
We deploy `ejdb 2.0.59` \ `iowow: 1.4.10` on many user's devices. Few of the user's devices crash at WAL. It's hard to reproduce the crash on test devcie. Any advise? Thanks a lot.

### 1. crash stack
```crash log
ABI: 'arm64'
Timestamp: 2022-10-27 06:33:23.695218742+0800
Process uptime: 0s
Cmdline: /system/bin/hiview
pid: 1307, tid: 4307, name: sysevent_servic  >>> /system/bin/hiview <<<
uid: 1000
tagged_addr_ctrl: 0000000000000001
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7f70e2212a6e
    x0  00007f70e2212a6e  x1  00000071a51aa003  x2  0000000000000008  x3  00000070e7193ae8
    x4  00000071a51aa00b  x5  00007f70e2212a76  x6  00038f0000000000  x7  00038f0000000000
    x8  00000070e2212000  x9  00000070e2212000  x10 000000719385904c  x11 0000000000000002
    x12 0000000000000036  x13 01d013c17412f074  x14 000000000000c9b8  x15 000000000cbe9621
    x16 000000719387b430  x17 000000718f4984e0  x18 00000070e1946000  x19 b40000710d642540
    x20 b40000710d642680  x21 0000000000000008  x22 00000071a51a9000  x23 0000000000012501
    x24 00000071a51a9fef  x25 00000071a51aa003  x26 00007f0000000a6e  x27 0000000000000000
    x28 00000000ffffffe7  x29 00000070e7193b10
    lr  00000071938590bc  sp  00000070e7193ac0  pc  000000718f4983d0  pst 0000000060001000

backtrace:
      #00 pc 00000000000853d0  lib64/bionic/libc.so (__memcpy+96) (BuildId: e887463ac42a8b4c415746f4ad81b598)
      #01 pc 00000000000180b8  /system/lib64/libiowow.z.so
      #02 pc 0000000000016af4  /system/lib64/libiowow.z.so
      #03 pc 0000000000016ee8  /system/lib64/libiowow.z.so
      #04 pc 00000000000eba70  lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: e887463ac42a8b4c415746f4ad81b598)
      #05 pc 000000000008b568  lib64/bionic/libc.so (__start_thread+64) (BuildId: e887463ac42a8b4c415746f4ad81b598)
```
### 2. iowow call stack
```shell
problem/0001_iowow_crash$ addr2line -e libiowow.z.so 0000000000016ee8 0000000000016af4 00000000000180b8
out/release/../../third_party/iowow/src/kv/iwal.c:837
out/release/../../third_party/iowow/src/kv/iwal.c:638
out/release/../../libs/ndk/sysroot/usr/include/bits/fortify/string.h:54
```

**Comment by adamansky** [comment] 2022-11-14 17:51
It may be related to #365 so try to fix it first.

**Comment by adamansky** [comment] 2022-11-18 05:50
Closing as duplicate of #365

**Closed by adamansky** 2022-11-18 05:50 UTC
